#!/usr/bin/env node
// Generates src/lib/city-data.ts — a static barrel of the selected city's
// city.json + pujas.json — so app code imports one module and never reads
// the other city's data. Runs automatically before build/dev/test/lint.
// Selected city: PB_CITY env override, else site.config.json.
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { resolveCity, loadCity } from "../src/lib/city.ts";

const cityId = resolveCity();
const city = loadCity(cityId);
const pujasJson = JSON.parse(
  readFileSync(
    path.join(process.cwd(), "data", "cities", cityId, "pujas.json"),
    "utf-8",
  ),
);

const out = `// AUTO-GENERATED by scripts/select-city.mjs — do not edit.
// City: ${cityId} (from site.config.json / PB_CITY).
import type { CityConfig } from "./city";
import type { PujoData } from "./types";

export const CITY_ID = ${JSON.stringify(cityId)} as const;
export const city = ${JSON.stringify(city, null, 2)} as CityConfig;
export const data = ${JSON.stringify(pujasJson, null, 2)} as PujoData;
`;

const dest = path.join(process.cwd(), "src", "lib", "city-data.ts");
mkdirSync(path.dirname(dest), { recursive: true });
writeFileSync(dest, out);
console.log(`select-city: wrote src/lib/city-data.ts (city=${cityId})`);
